### ISSUE TITLE
how to deal with Lotus archive file?

### ISSUE THREAD

**Issue by vincent-lucy** [libyal/libvsmbr#6]
Hi,

do you know if you can open /transform any archive file with free software ?

Regards,

vincent

**Comment by joachimmetz** [comment]
how is this question relevant for this project?

**Comment by vincent-lucy** [comment]
Yep sorry for the delay, i don't know for your interest, a user come to me with (very) old archive from an ancient work, and for now has no access to her data.
She searches another way.
Good continuation.
